spring.application.name=sdk-analyzer
server.port=8080

# Logging
logging.file.name=logs/sdk-analyzer.log
logging.level.root=INFO
logging.level.com.senior.analyzer=DEBUG
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5level [%thread] %logger{36} - %msg%n
